nemos-images-reference-lunar/aarch64/appliance.kiwi, nemos-images-reference-lunar/x86/appliance.kiwi
This adds the missing iptables package which is required for firewall management
=> nemos-images-reference-lunar: x86, aarch64: add iptables

nemos-images-reference-lunar/aarch64/pre_disk_sync.sh, nemos-images-reference-lunar/x86/pre_disk_sync.sh
`dmsetup` is a useful tool for managing and querying the status of the device mappings running on the system (`dm-verity`, `dm-crypt`, and `dm-integrity`). We should keep this tool in the image.
=> nemos-images-reference-lunar: x86, aarch64: do not remove dmsetup

nemos-images-embedded-lunar/kiwi.yaml
This brings the configuration more in line with the configration for nemos-images-reference-lunar, and allows building without an additional external configuration file.
=> nemos-images-embedded-lunar: disable runtime check for dracut-kiwi-overlay

nemos-images-reference-lunar/aarch64/appliance.kiwi, nemos-images-reference-lunar/x86/appliance.kiwi
pbkdf2 is considered much less secure than the default argon2id, and it was only selected because the default argon2id settings can cause out-of-memory errors on small systems. This can however be worked around by manually setting the argon2id parameters to require less memory, while still making use of the much more secure pbkdf scheme.
=> nemos-images-reference-lunar: aarch64, x86: adjust pbkdf parameters

debian/control
Add the dependencies which are required for building the images to the Debian package.
=> debian: add Debian package dependencies

.github/workflows/debian-packages.yaml, .github/workflows/nemos-images-minimal-lunar.yaml, .github/workflows/nemos-images-reference-lunar.yaml
Both minimal and reference images are now automatically built on pull requests.
This uses the NemOS Kiwi PPA to provide Kiwi for Ubuntu 22.04.
=> .github: workflows: add actions to build NemOS images

nemos-images-minimal-lunar/qemu-amd64/appliance.kiwi, nemos-images-minimal-lunar/qemu-amd64/pre_disk_sync.sh, nemos-images-minimal-lunar/qemu-arm64/appliance.kiwi, nemos-images-minimal-lunar/qemu-arm64/pre_disk_sync.sh, nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-amd64/pre_disk_sync.sh, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/pre_disk_sync.sh
Instead of using the standard linux-generic kernel, we can use the new tailor-made linux-s32 kernel from the NemOS PPA for building the images. This kernel is smaller and has specific configuration options which are helpful for NemOS development.
=> nemos-images-{minimal,reference}-lunar: qemu-{amd64,arm64}: use linux-s32

nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi
`aes-gcm-random` is explicitly mentioned in the cryptsetup release notes as insecure. We should avoid using this cipher, and instead use the more secure `aegis128-random`, which also supports the `aead` integrity mode.
=> nemos-images-reference-lunar: qemu-{amd64,arm64}: update crypt cipher

nemos-images-reference-lunar/qemu-amd64/pre_disk_sync.sh, nemos-images-reference-lunar/qemu-arm64/pre_disk_sync.sh
These packages are required for running the checkbox snap, so we should not remove them in the development profile.
=> nemos-images-reference-lunar: do not remove bash and python3

nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi
This package is used for tracking total system uptime.
=> nemos-images-reference-lunar: qemu-{amd64,arm64}: add tuptime package

nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-amd64/root/etc/polkit-1/localauthority/10-vendor.d/admin-org.freedesktop.login1.pkla, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/root/polkit-1/localauthority/10-vendor.d/admin-org.freedesktop.login1.pkla
This adds the polkitd utility, which allows adding policies which determine what non-root users can do.
This also adds a default policy which allows the "admin" user to power-off, reboot, and halt the system using dbus access to logind.
This can be demonstrated by calling the following command as the admin user, which will shutdown the system:
dbus-send --system --print-reply --dest=org.freedesktop.login1 \
/org/freedesktop/login1 "org.freedesktop.login1.Manager.PowerOff" \
boolean:true
=> nemos-images-reference-lunar: qemu-{arm64,amd64}: add polkitd

nemos-images-minimal-lunar/qemu-amd64/config.sh, nemos-images-minimal-lunar/qemu-amd64/pre_disk_sync.sh, nemos-images-minimal-lunar/qemu-arm64/config.sh, nemos-images-minimal-lunar/qemu-arm64/pre_disk_sync.sh, nemos-images-reference-lunar/qemu-amd64/config.sh, nemos-images-reference-lunar/qemu-amd64/pre_disk_sync.sh, nemos-images-reference-lunar/qemu-arm64/config.sh, nemos-images-reference-lunar/qemu-arm64/pre_disk_sync.sh
Many of the functions carried out by these scripts are already the default in Ubuntu and are therefore not required. Remove them to simplify the scripts.
Additionally, some packages seem to leave behind some header files in /usr/src; delete them to reclaim space.
=> Improve cleanup scripts

nemos-images-minimal-lunar/qemu-amd64/appliance.kiwi, nemos-images-minimal-lunar/qemu-amd64/pre_disk_sync.sh, nemos-images-minimal-lunar/qemu-amd64/root/etc/netplan/00-netplan.yaml, nemos-images-minimal-lunar/qemu-amd64/root/etc/systemd/network/20-local.network, nemos-images-minimal-lunar/qemu-amd64/root/etc/udev/rules.d/70-persistent-net.rules, nemos-images-minimal-lunar/qemu-arm64/appliance.kiwi, nemos-images-minimal-lunar/qemu-arm64/pre_disk_sync.sh, nemos-images-minimal-lunar/qemu-arm64/root/etc/netplan/00-netplan.yaml, nemos-images-minimal-lunar/qemu-arm64/root/etc/systemd/network/20-local.network, nemos-images-minimal-lunar/qemu-arm64/root/etc/udev/rules.d/70-persistent-net.rules, nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-amd64/pre_disk_sync.sh, nemos-images-reference-lunar/qemu-amd64/root/etc/netplan/00-netplan.yaml, nemos-images-reference-lunar/qemu-amd64/root/etc/systemd/network/20-local.network, nemos-images-reference-lunar/qemu-amd64/root/etc/udev/rules.d/70-persistent-net.rules, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/pre_disk_sync.sh, nemos-images-reference-lunar/qemu-arm64/root/etc/netplan/00-netplan.yaml, nemos-images-reference-lunar/qemu-arm64/root/etc/systemd/network/20-local.network, nemos-images-reference-lunar/qemu-arm64/root/etc/udev/rules.d/70-persistent-net.rules
Replace the usage of raw systemd-networkd and udev rules with
netplan.io, which can do the job of both in one YAML file, simplifying
the network configurations.
Additionally, do not remove python3 packages from the rootfs, as these are required
for netplan.io. This particular change actually has very little effect on the disk
usage; python3.10 doesn't exist in lunar (as it uses 3.11), so removing
the package was essentially a no-op before. Removing the python3 package
basically just removes the symlink for python3 to python3.11, which also
doesn't have an impact on the rootfs size.
=> Use netplan.io for network management

.github/workflows/debian-packages.yaml, .github/workflows/nemos-images-minimal-lunar.yaml, .github/workflows/nemos-images-reference-lunar.yaml, nemos-images-minimal-lunar/qemu-amd64/pre_disk_sync.sh, nemos-images-minimal-lunar/qemu-arm64/pre_disk_sync.sh, spread.yaml, tests/spread/os-information-23.04/task.yaml, tests/spread/storage-configuration/task.yaml
This changeset adds the required files for running tests inside generated VM images using the spread framework (https://github.com/snapcore/spread).
Spread tests can be run by running the following commands (the build directory refers to the location where the Kiwi images were built):
```
mkdir -p ~/.spread/qemu
cp build/nemos-image-minimal-lunar.x86_64-1.0.1.qcow2 \
~/.spread/qemu/nemos-image-minimal-lunar.img
cp build/nemos-image-reference-lunar.x86_64-1.0.1.qcow2 \
~/.spread/qemu/nemos-image-reference-lunar.img
spread -v
```
These tests can be used to automatically verify that features are present and enabled in the generated images.
=> Add integration tests using the spread framework

nemos-images-minimal-lunar/qemu-amd64/appliance.kiwi, nemos-images-minimal-lunar/qemu-amd64/root/etc/fstab.append, nemos-images-minimal-lunar/qemu-arm64/root/etc/fstab.append, nemos-images-minimal-lunar/run_qemu_amd64.sh, nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-amd64/root/etc/fstab.append, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/root/etc/fstab.append, spread.yaml
Set the console to `serial` as the default `gfxterm` does not work in the VM (as the VM does not have a graphics output).
Additionally, set the timeout to `0` to remove the boot delay. This mostly invalidates the need for setting the console to `serial`, as the console won't appear, but it's helpful to explicitly set these variables in case a user wants to add a timeout for debugging purposes.
=> nemos-images-*-lunar: qemu-*: update grub parameters

.github/workflows/nemos-images-minimal-lunar.yaml, .github/workflows/nemos-images-reference-lunar.yaml, nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-amd64/root/etc/dracut.conf.d/90-preload.conf, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/root/etc/dracut.conf.d/90-preload.conf, spread.yaml, tests/spread/storage-configuration/task.yaml
Use the new kiwi-dracut-overlay and kiwi-dracut-verity modules from the latest version of Kiwi instead of the custom modules.
Additionally, add the Kiwi backports PPA from the NemOS project to make use of the latest version of Kiwi.
=> nemos-images-reference-lunar: qemu-*: use new dracut modules

nemos-images-minimal-lunar/qemu-amd64/config.sh, nemos-images-minimal-lunar/qemu-amd64/root/etc/systemd/journald.conf, nemos-images-minimal-lunar/qemu-arm64/config.sh, nemos-images-minimal-lunar/qemu-arm64/root/etc/systemd/journald.conf, nemos-images-minimal-lunar/s32g274ardb2/config.sh, nemos-images-minimal-lunar/s32g274ardb2/root/etc/systemd/journald.conf, nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-amd64/config.sh, nemos-images-reference-lunar/qemu-amd64/root/etc/systemd/journald.conf, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/config.sh, nemos-images-reference-lunar/qemu-arm64/root/etc/systemd/journald.conf, nemos-images-reference-lunar/s32g274ardb2/appliance.kiwi, nemos-images-reference-lunar/s32g274ardb2/config.sh, nemos-images-reference-lunar/s32g274ardb2/root/etc/systemd/journald.conf
Add systemd-coredump to the reference images to allow capturing application core dumps. 
As part of this, re-enable journald storage as it is required by systemd-coredump.
=> Add systemd-coredump

nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/s32g274ardb2/appliance.kiwi
`apport` has been replaced by `systemd-coredump`, so remove `apport` from the development profile.
=> nemos-images-reference-lunar: *: remove apport in the development profile

nemos-images-minimal-lunar/qemu-amd64/appliance.kiwi, nemos-images-minimal-lunar/qemu-arm64/appliance.kiwi, nemos-images-minimal-lunar/s32g274ardb2/appliance.kiwi, nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/s32g274ardb2/appliance.kiwi
Add the admin user to the systemd-journal and systemd-coredump to demonstrate the permissions handling for controlling access to systemd logging features.
=> ERL-265: nemos-images-reference-lunar: *: add admin user to log groups 

nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-amd64/root/etc/dracut.conf.d/91-pstore.conf, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/root/etc/dracut.conf.d/91-pstore.conf, run_qemu.sh
Add the ability to make use of the EFI variable storage to enable pstore functionality, which allows saving kernel logs to the EFI storage in case of kernel crashes.
=> ERL-294: nemos-images-reference-lunar: qemu-*: enable pstore support and usage

nemos-images-reference-lunar/qemu-amd64/appliance.kiwi, nemos-images-reference-lunar/qemu-arm64/appliance.kiwi, nemos-images-reference-lunar/s32g274ardb2/appliance.kiwi
Sample output on the system:
```
DUMP_MODE:              kdump
USE_KDUMP:              1
KDUMP_COREDIR:          /var/crash
crashkernel addr: 0x27000000
/var/lib/kdump/vmlinuz: symbolic link to /boot/vmlinuz-5.15.0-1017-s32-eb
kdump initrd:
/var/lib/kdump/initrd.img: symbolic link to /var/lib/kdump/initrd.img-5.15.0-1017-s32-eb
current state:    ready to kdump
kexec command:
/sbin/kexec -p --command-line="BOOT_IMAGE=/vmlinuz-5.15.0-1017-s32-eb root=overlay:MAPPER=verityRoot verityroot=/dev/disk/by-partlabel/p.lxreadonly rd.root.overlay.write=/dev/mapper/luks rd.luks=yes rootwait ro console=ttyS0 rd.systemd.verity=1 verityroot=/dev/disk/by-partlabel/p.lxreadonly rd.root.overlay.write=/dev/mapper/luks rd.luks=yes rootwait pstore.backend=efi reset_devices …
```
=> ERL-293: nemos-images-reference-lunar: add kdump-tools package

run_qemu.sh
With kdump-tools reserving a large chunk of RAM, there is not enough RAM leftover for testing with snapd. Increase the default RAM size to get around this.
=> ERL-424: run_qemu.sh: increase default RAM size

nemos-images-minimal-mantic/qemu-amd64/appliance.kiwi, nemos-images-minimal-mantic/qemu-amd64/install_grub.sh, nemos-images-minimal-mantic/qemu-arm64/appliance.kiwi, nemos-images-minimal-mantic/qemu-arm64/install_grub.sh, nemos-images-reference-mantic/qemu-amd64/appliance.kiwi, nemos-images-reference-mantic/qemu-amd64/install_grub.sh, nemos-images-reference-mantic/qemu-arm64/appliance.kiwi, nemos-images-reference-mantic/qemu-arm64/install_grub.sh
Kiwi seems to generate an invalid configuration for Grub 2.12, causing the images to fail to boot. Manually install Grub and Shim according to the standard Ubuntu UEFI layout to get around this.
=> ERL-466: nemos-images-*-mantic: qemu-*: fix EFI boot on Grub 2.12
